### ISSUE TITLE
System.MissingMethodException when trying file upload

### ISSUE THREAD

**Issue by stevegray12** [kevinobee/Sitecore.Ship#57]
Sitecore version xp 8.1
sitecore ship version 0.3.5

when attempting a post to [servername]/services/package/install/fileupload

I get the following 500 error.

Nancy.RequestExecutionException: Oh noes! ---> System.MissingMethodException: Method not found: 'System.String Sitecore.Update.UpdateHelper.SaveInstallationMessages(System.Collections.Generic.List`1, System.String)'.
   at Sitecore.Ship.Infrastructure.Update.UpdatePackageRunner.Execute(String packagePath, Boolean disableIndexing)
   at Sitecore.Ship.Core.PackageRepository.AddPackage(InstallPackage package) in d:\Development\SCC\ship\src\Sitecore.Ship.Core\PackageRepository.cs:line 17
   at Sitecore.Ship.Package.Install.InstallerModule.InstallUploadPackage(Object o) in d:\Development\SCC\ship\src\Sitecore.Ship\Package\Install\InstallerModule.cs:line 108
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, IPipelines pipelines)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by pveller** [comment]
Take a look at issue #30. The solution is to use `Sitecore.Ship` version 0.4 that you can download off of the alpha MyGet feed: https://www.myget.org/F/sitecore-ship-prerelease/api/v2/package

**Comment by stevegray12** [comment]
Thanks, does anybody know when it will become an official release?

**Comment by pveller** [comment]
I can't tell. @kevinobee had big plans to rewrite with SSC and WebAPI and haven't pushed 0.4 to NuGet.

**Comment by kevinobee** [comment]
The MyGet 0.4.0 pre-release packages are on the [NuGet gallery](https://www.nuget.org/packages?q=sitecore.ship) now. 

Interested to hear if these solve your issue @stevegray12

**Comment by stevegray12** [comment]
@kevinobee. The version we pulled from mygit did solve the issue after we solved some reference issues with ANTLR3. I will pick up the officall release today and update you monday.

**Comment by stevegray12** [comment]
@kevinobee  All working many thanks.
