### ISSUE TITLE
File Upload seems to work but throws error on SaveInstallationMessages

### ISSUE THREAD

**Issue by craigagnew** [kevinobee/Sitecore.Ship#68]
Hello,

We have automated builds running through Jenkins/Powershell to deploy Sitecore regularly. Everything seems to work fine, however we've noticed during the step to deploy the *.update packages an error occurs, but the items seem to have been created/updated on the server.

The process involves deployment of 3 *.update files. The first seems to deploy without issue, while the other two deploy but report an error at the following line: 

https://github.com/kevinobee/Sitecore.Ship/blob/release/0.4.0/src/Sitecore.Ship.Infrastructure/Update/UpdatePackageRunner.cs#L90

An example of the stack trace from the Sitecore log is below:

`6008 17:28:19 INFO  Installing item '/sitecore/content/Home/Test/Test Page 1'
6008 17:28:19 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:19 INFO  Scripts in cache: 1
6008 17:28:19 INFO  Creating script with key master6826A27606EA4046826EE30FD2E89327
6008 17:28:19 INFO  Scripts in cache: 2
6008 17:28:19 INFO  Cleared script cache
6008 17:28:20 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:20 INFO  Scripts in cache: 1
6008 17:28:20 INFO  Creating script with key master6826A27606EA4046826EE30FD2E89327
6008 17:28:20 INFO  Scripts in cache: 2
6008 17:28:20 INFO  Cleared script cache
6008 17:28:20 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:20 INFO  Scripts in cache: 1
6008 17:28:20 INFO  Creating script with key master6826A27606EA4046826EE30FD2E89327
6008 17:28:20 INFO  Scripts in cache: 2
6008 17:28:20 INFO  Cleared script cache
6008 17:28:20 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:20 INFO  Scripts in cache: 1
6008 17:28:20 INFO  Creating script with key master6826A27606EA4046826EE30FD2E89327
6008 17:28:20 INFO  Scripts in cache: 2
6008 17:28:20 INFO  Cleared script cache
6008 17:28:20 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:21 INFO  Scripts in cache: 1
6008 17:28:21 INFO  Creating script with key master6826A27606EA4046826EE30FD2E89327
6008 17:28:21 INFO  Scripts in cache: 2
6008 17:28:21 INFO  Cleared script cache
6008 17:28:21 INFO  Installing item '/sitecore/content/Home/Test/Test Page 2'
6008 17:28:21 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:21 INFO  Scripts in cache: 1
6008 17:28:21 INFO  Creating script with key master6826A27606EA4046826EE30FD2E89327
6008 17:28:21 INFO  Scripts in cache: 2
6008 17:28:21 INFO  Cleared script cache
6008 17:28:21 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:21 INFO  Scripts in cache: 1
6008 17:28:21 INFO  Creating script with key master6826A27606EA4046826EE30FD2E89327
6008 17:28:21 INFO  Scripts in cache: 2
6008 17:28:21 INFO  Cleared script cache
6008 17:28:21 INFO  Creating script with key master5862787EDD1B45559C1C4EFAD12AFD51
6008 17:28:22 ERROR Execution of action failed. Rule item ID: {C1740EDC-A6F7-405F-97C7-E6A73530A9A8}, action item ID: {94C5C335-0902-4B45-B528-11B220005DD7}
Exception: System.Threading.ThreadAbortException
Message: Thread was being aborted.
Source: mscorlib
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at System.CodeDom.Compiler.Executor.ExecWaitWithCaptureUnimpersonated(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at System.CodeDom.Compiler.Executor.ExecWaitWithCapture(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at Microsoft.CSharp.CSharpCodeGenerator.Compile(CompilerParameters options, String compilerDirectory, String compilerExe, String arguments, String& outputFile, Int32& nativeReturnValue, String trueArgs)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at Sitecore.CodeDom.Scripts.ScriptFactory.Compile(IEnumerable`1 references, String code, String language, CompilerParameters options)
   at Sitecore.CodeDom.Scripts.ScriptFactory.Compile(String cacheKey, IEnumerable`1 references, String code, String language)
   at Sitecore.CodeDom.Scripts.ItemScripts.InvokeDefaultMethod[T](Item item, Object[] parameters)
   at Sitecore.Rules.Actions.RunScript`1.Apply(T ruleContext)
   at Sitecore.Rules.RuleList`1.Run(T ruleContext, Boolean stopOnFirstMatching, Int32& executedRulesCount)

6008 17:28:22 ERROR Failed to record installation messages
6008 17:28:22 ERROR Application error.
Exception: System.Web.HttpException
Message: Request timed out.`

The "Request timed out" would appear to be a red herring in this case, as the build in question for this example took 7 min 44 sec to complete, with our executionTimeout set to an arbitrary 1800 seconds (30 min).

Has anyone come across a similar issue at all?

We are using Sitecore 8.1 Update 2 and Sitecore.Ship 0.4.0.

Thanks,
Craig

**Comment by dharnitski** [comment]
This pull request should help - https://github.com/kevinobee/Sitecore.Ship/pull/69
