### ISSUE TITLE
[TypeLoadException]: Method FormatValueForIndexStorage in type Coveo.Framework.Conversion.CoveoIndexField StorageValueFormatter from assembly Coveo.Framework does not have an implementation

### ISSUE THREAD

**Issue by prabhatsingh2011** [kevinobee/Sitecore.Ship#71]
Hi ,

I am getting below error. Please help

[TypeLoadException]: Method FormatValueForIndexStorage in type Coveo.Framework.Conversion.CoveoIndexField
StorageValueFormatter from assembly Coveo.Framework does not have an implementation.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at Nancy.TinyIoc.TinyIoCContainer.<AutoRegisterInternal>b__13(Type type)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Nancy.TinyIoc.TinyIoCContainer.AutoRegisterInternal(IEnumerable`1 assemblies, Boolean ignoreDuplicateImplementatio
ns, Func`2 registrationPredicate)
   at Nancy.DefaultNancyBootstrapper.AutoRegister(TinyIoCContainer container, IEnumerable`1 ignoredAssemblies)
   at Sitecore.Ship.DefaultBootstrapper.ConfigureApplicationContainer(TinyIoCContainer container)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Hosting.Aspnet.NancyHttpRequestHandler..cctor()
[TypeInitializationException]: The type initializer for &#39;Nancy.Hosting.Aspnet.NancyHttpRequestHandler&#39; threw an
exception.
   at Nancy.Hosting.Aspnet.NancyHttpRequestHandler..ctor()
[TargetInvocationException]: Exception has been thrown by the target of an invocation.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCache
d, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark
& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture,
 Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo cul
ture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo cul
ture)
   at System.Web.HttpRuntime.CreateNonPublicInstance(Type type, Object[] args)
   at System.Web.Configuration.HandlerFactoryCache..ctor(String type)
   at System.Web.HttpApplication.GetFactory(String type)
   at System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-->PS C:\Users\server_admin> ^A

**Comment by prabhatsingh2011** [comment]
Aah , i started using Sitecore.Ship.AspNet which is nancy independent and now able to install the package properly.
